{
  "hash": "6b200390bc5dc498ac384b3fd89befe0",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Tips Dataset\"\nauthor: \"Musie Beyene\"\ndate: \"2024-11-14\"\ncategories: [analysis]\nimage: \"image.jpg\"\n---\n\n## Goals\nIn this blogpost we will demonstrate some common exploratory data analysis (EDA) techniques using the [tips dataset](https://seaborn.pydata.org/generated/seaborn.load_dataset.html#seaborn.load_dataset). This dataset is a record of real visits to a restaurant collected by a waiter. It is a small set of structured data with a good mix of categorical and numerical features. This affords us the opportunity to apply a surprisingly wide range of EDA techniques in a contextualised analysis, demostrating the utility of these techniques and the associated python packages.\n\nThe objective is to demonstrate analysis techniques, including visualisation, for\n\n1. univariate \n    - categorical \n    - numerical\n\n\n2. bivariate \n    - categorical \n    - numerical and\n    - mixed \n\nvariables. We will use\n\n- [pandas](https://pandas.pydata.org/) for data wrangling,\n- [seaborn](https://seaborn.pydata.org/index.html) and [matplotlib](https://matplotlib.org/)for visualisation and\n- [statsmodels](https://www.statsmodels.org/stable/index.html) for statistical analysis.\n\n## Introduction\n\nHave you ever wondered if your tipping habits are typical? If tipping depends on the day of the week or, how exactly the total bill affects tipping? Well, we can explore some of these and other questions for a widely used dataset of real restaurant visits collected by a waiter.\n\nThe [tips dataset](https://seaborn.pydata.org/generated/seaborn.load_dataset.html#seaborn.load_dataset), as it is known, has 244 records each with 7 features. The features are\n\n\n|   Feature |                   Description                     |  Data Type | Range/Levels            |\n| --------- | --------------------------------------------------|------------|-------------------------| \n| total_bill| The total amount of the bill in dollars           | numeric    |    [3.07, 50.81] USD    |\n| tip       | The tip amount in dollars                         | numeric    |    [1.00, 10.00] USD    |\n| sex       | The gender of the person who paid the bill        | categorical|    Male, Female         |\n| smoker    | Indicates whether there were smokers in the party | categorical|    Yes, No              |\n| day       | The day of the week the meal was consumed         | categorical|    Thur, Fri, Sat, Sun  |\n| time      | The time of day the meal was consumed             | categorical|    Lunch, Dinner        |\n| size      | The size(in numer of persons) of the party        | numeric    |    [1, 6] Persons       |\n: Tips dataset features {#tbl-fields_description}\n\n### Considerations : Context for the Data\n\nWhen performing analysis it is important to have some context for the data. It is good practice to consider the following questions\n\n- how \n- why \n- where and \n- when \n\nthe data was collected. This will determine what you can expect from your analysis and how you can present your findings.\n\nFor example, the tips data can potentially allow us to determine the takings of the restaurant for the period represented (assuming we have that information). However, this assumes the waiter recorded all takings of this period. It might be that the waiter, motivated by his own tip takings, only recorded visits that he/she served. Perhaps the waiter only works part time or maybe, given the sheer volume of visits, the waiter might have chosen a random set of visits to record. \n\nNow, suppose that the waiter recorded all transactions correctly and that we are able to calculate the takings (or any other statistic) correctly. Can we take the statistics to be representative or typical of visits currently. Was the data collected before the volume and composition of visits changed dramatically following the construction of a football stadium nearby. Perhaps the data was collected during a festival, a particularly busy period for the restaurant. All these questions are important.\n\nFor our purposes we will assume the data to be representative in every sense and proceed to ask questions,and demonstrate analytical techniques, unrestricted.\n\n## The Data\n\n### Loading and inspecting the dataset\n\nAs mensioned earlier, the dataset is available as a [pandas dataframe](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html) from the seaborn library. So, let us load pandas and seaborn. We will also use seaborn as our primary visualization tool however, we will also use matplotlib. Additionally, we will use [statsmodels](https://www.statsmodels.org/stable/index.html) for statistical analysis, in particular for testing statistical hypothesis.\n\nSo, let us import these libraries, load our data and inspect the first few records.\n\n::: {#6bc6c8d5 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport statsmodels.api as sm\n\ndf_tips = sns.load_dataset(\"tips\")\ndf_tips.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=61}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>total_bill</th>\n      <th>tip</th>\n      <th>sex</th>\n      <th>smoker</th>\n      <th>day</th>\n      <th>time</th>\n      <th>size</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>16.99</td>\n      <td>1.01</td>\n      <td>Female</td>\n      <td>No</td>\n      <td>Sun</td>\n      <td>Dinner</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>10.34</td>\n      <td>1.66</td>\n      <td>Male</td>\n      <td>No</td>\n      <td>Sun</td>\n      <td>Dinner</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>21.01</td>\n      <td>3.50</td>\n      <td>Male</td>\n      <td>No</td>\n      <td>Sun</td>\n      <td>Dinner</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>23.68</td>\n      <td>3.31</td>\n      <td>Male</td>\n      <td>No</td>\n      <td>Sun</td>\n      <td>Dinner</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>24.59</td>\n      <td>3.61</td>\n      <td>Female</td>\n      <td>No</td>\n      <td>Sun</td>\n      <td>Dinner</td>\n      <td>4</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nLet us examine what categories pandas has assigned to each variable.\n\n::: {#6f35c07d .cell execution_count=2}\n``` {.python .cell-code}\ndf_tips.dtypes\n```\n\n::: {.cell-output .cell-output-display execution_count=62}\n```\ntotal_bill     float64\ntip            float64\nsex           category\nsmoker        category\nday           category\ntime          category\nsize             int64\ndtype: object\n```\n:::\n:::\n\n\nIt is common for datasets to have missing data. The `info()` method of a `DataFrame` can be used to examine the number of missing values in each column.\n\n::: {#330417e3 .cell execution_count=3}\n``` {.python .cell-code}\ndf_tips.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 244 entries, 0 to 243\nData columns (total 7 columns):\n #   Column      Non-Null Count  Dtype   \n---  ------      --------------  -----   \n 0   total_bill  244 non-null    float64 \n 1   tip         244 non-null    float64 \n 2   sex         244 non-null    category\n 3   smoker      244 non-null    category\n 4   day         244 non-null    category\n 5   time        244 non-null    category\n 6   size        244 non-null    int64   \ndtypes: category(4), float64(2), int64(1)\nmemory usage: 7.4 KB\n```\n:::\n:::\n\n\nHere we see that there are a total of 244 records inxed 0 to 243. `info()` also  gives us the data type designation of each column (variable/field). There are no missing values on this set as indicated by 244 non-null counts for all the columns. In case of missing values, the Non-Null Count column displays the number of null values. This is of course the count by column. Finally, we are told size of the DataFrame in memory is 7.4 kilobytes.\n\nFor numerical variables we can get the five-point summary statistics, and more, as follows\n\n::: {#ad05bee9 .cell execution_count=4}\n``` {.python .cell-code}\ndf_tips.describe()\n```\n\n::: {.cell-output .cell-output-display execution_count=64}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>total_bill</th>\n      <th>tip</th>\n      <th>size</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>244.000000</td>\n      <td>244.000000</td>\n      <td>244.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>19.785943</td>\n      <td>2.998279</td>\n      <td>2.569672</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>8.902412</td>\n      <td>1.383638</td>\n      <td>0.951100</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>3.070000</td>\n      <td>1.000000</td>\n      <td>1.000000</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>13.347500</td>\n      <td>2.000000</td>\n      <td>2.000000</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>17.795000</td>\n      <td>2.900000</td>\n      <td>2.000000</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>24.127500</td>\n      <td>3.562500</td>\n      <td>3.000000</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>50.810000</td>\n      <td>10.000000</td>\n      <td>6.000000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nWe can see that the summary from `info()` and `describe()` are consistent and agree with table @tbl-fields_description.\n\n\n\n\n\n\n----\n\n\n\n\n\n\nLet us plot visit counts by days of the week.\n\n::: {#fc667d6a .cell execution_count=5}\n``` {.python .cell-code}\nplt.style.use(\"bmh\")\n\nplt.title(\"Visit Counts by Day of the Week\")\nsns.countplot(x=\"day\", data=df_tips)\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-6-output-1.png){width=583 height=450}\n:::\n:::\n\n\nWe can also examine the distribution of visit counts by day of the week and sex.\n\n::: {#59f45c69 .cell execution_count=6}\n``` {.python .cell-code}\nplt.title(\"Visit Counts by Day of the Week\")\nsns.countplot(x=\"day\", hue=\"sex\", data=df_tips);\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-7-output-1.png){width=583 height=450}\n:::\n:::\n\n\n## Distribution of spending by gender\n\n::: {#12eb324e .cell execution_count=7}\n``` {.python .cell-code}\nplt.title(\"Distribution of Spending by Gender\")\nsns.histplot(x=\"total_bill\", hue=\"sex\", data=df_tips, fill=True);\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-8-output-1.png){width=583 height=451}\n:::\n:::\n\n\n## Distribution of spending by smoking status\n\n::: {#c833a1ac .cell execution_count=8}\n``` {.python .cell-code}\nplt.title(\"Distribution of Spending by Smoking Status\")\nsns.kdeplot(x=\"total_bill\", hue=\"smoker\", data=df_tips, fill=True);\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-9-output-1.png){width=604 height=451}\n:::\n:::\n\n\n## Distribution of spending by day\n\n::: {#471a4988 .cell execution_count=9}\n``` {.python .cell-code}\nplt.title(\"Distribution of Spending by Day\")\nsns.histplot(x=\"total_bill\", hue=\"day\", data=df_tips, fill=True);\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-10-output-1.png){width=583 height=451}\n:::\n:::\n\n\nWe can also include boxplots.\n\n::: {#22a60292 .cell execution_count=10}\n``` {.python .cell-code}\nplt.title(\"Distribution of Spending by Day\")\nsns.boxplot(x=\"day\", y=\"total_bill\", data=df_tips);\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-11-output-1.png){width=583 height=450}\n:::\n:::\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}